apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      versao: green
  template:
    metadata:
      labels:
        app: web
        versao: green
    spec:
      containers:
      - name: web
        image: fabricioveronez/web-color:green
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      versao: blue
  template:
    metadata:
      labels:
        app: web
        versao: blue
    spec:
      containers:
      - name: web
        image: fabricioveronez/web-color:blue
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
    versao: green
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  type: "LoadBalancer"