apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-color
spec:
  selector:
    matchLabels:
      app: web-color
  template:
    metadata:
      labels:
        app: web-color
    spec:
      containers:
      - name: web-color
        image: fabricioveronez/web-color:blue
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-color
spec:
  selector:
    app: web-color
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer