apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-bbb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-bbb
  template:
    metadata:
      labels:
        app: nginx-bbb
    spec:
      containers:
      - name: nginx-bbb
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
