apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-blue
  template:
    metadata:
      labels:
        app: web-blue
    spec:
      containers:
      - name: web-blue
        image: fabricioveronez/web-color:blue
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 125m
            memory: 128Mi
      tolerations:
        - key: gpu
          operator: "Equal"
          value: "true"
          effect: NoSchedule